# Generated by Django 5.2.6 on 2025-09-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_namespace',
            field=models.CharField(default=1, help_text="O 'app_name' definido no urls.py da aplicação. Ex: 'phoenix'", max_length=50, unique=True, verbose_name='Namespace da Aplicação (para URLs)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(help_text='Ex: Phoenix, Análise de Dados', max_length=100, unique=True, verbose_name='Nome da Aplicação'),
        ),
        migrations.AlterField(
            model_name='module',
            name='view_name',
            field=models.CharField(help_text="O 'name' da URL no urls.py. Ex: 'dashboard', 'user_list'", max_length=100, verbose_name='Nome da View (url name)'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('application', 'view_name')},
        ),
    ]
