# Generated by Django 5.2.6 on 2025-09-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_application_app_namespace_alter_application_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10, verbose_name='Tema'),
        ),
    ]
